apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: swift
  template:
    metadata:
      labels:
        name: swift
    spec:
      containers:
      - name: swift
        image: fnndsc/docker-swift-onlyone:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: cube-secrets