apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: mmurakam/chris:3 #fnndsc/chris
        ports:
        - containerPort: 6900
        envFrom:
        - configMapRef:
            name: worker-config
        command: ["celery"]
        args: ["-A", "core", "worker", "-c", "1", "-l", "DEBUG", "-Q", "main"]