apiVersion: v1
kind: Service
metadata:
  name: chris-store
  labels:
    name: chris-store
spec:
  type: NodePort
  ports:
  - port: 8010
    targetPort: 8010
    nodePort: 30010
  selector:
    name: chris-store