apiVersion: v1
kind: Service
metadata:
  name: chris-store-db
  labels:
    name: chris-store-db
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    name: chris-store-db