apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chris-db
  template:
    metadata:
      labels:
        name: chris-db
    spec:
      containers:
      - name: mysql
        image: mysql:5
        ports:
        - containerPort: 5672
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootp
        - name: MYSQL_DATABASE
          value: chris_dev
        - name: MYSQL_USER
          value: chris
        - name: MYSQL_PASSWORD
          value: Chris1234