kind: Kustomization

configMapGenerator:
- name: chris-store-config
  env: configs/chris-store.env
- name: chris-db-config
  env: configs/chris-db.env
- name: chris-store-db-config
  env: configs/chris-store-db.env
- name: swift-service-config
  env: configs/swift-service.env
- name: worker-config
  env: configs/worker.env

resources:
- resources/rabbitmq-deployment.yaml
- resources/rabbitmq-service.yaml
- resources/chris-store-db-deployment.yaml
- resources/chris-store-db-service.yaml
- resources/chris-db-deployment.yaml
- resources/chris-db-service.yaml
- resources/chris-store-deployment.yaml
- resources/chris-store-service.yaml
- resources/chris-deployment.yaml
- resources/chris-service.yaml
- resources/worker-deployment.yaml
- resources/worker-service.yaml
- resources/swift-deployment.yaml
- resources/swift-service.yaml
- resources/pfcon-deployment.yaml
- resources/pfcon-service.yaml
- resources/pfioh-deployment.yaml
- resources/pfioh-service.yaml
- resources/pman-deployment.yaml
- resources/pman-service.yaml
- resources/scheduler-deployment.yaml